import Link from "next/link";

export const metadata = {
    title: 'Blogs | Next App',
    description: 'Generated by create next app',
  }


  const BLogs = [
    {
        id: 1, 
        year: 2023, 
        title: 'title1'
    },
    {
        id: 2, 
        year: 2023, 
        title: 'title 2'
    },
    {
        id: 3, 
        year: 2023, 
        title: 'title 3'
    },
    {
        id: 4, 
        year: 2023, 
        title: 'title 4'
    },
  ]
  

const BLogsPage = () => {
  return (
    <div className="container mx-auto">
        {
            BLogs.map(({id, year, title}) => 
            <Link key={id} className="block border border-blue-600 p-2 my-2" href={{
                pathname:`/blogs/${year}/${id}`,
                query:{
                    title:title,
                }
            }}>{title}</Link>
            )
        }
    </div>
  )
}

export default BLogsPage;