export const metadata = {
    title: 'Add Product | Dashboard | Next App',
    description: 'Generated by create next app',
  }

const AddProduct =()=> {
    return (
        <>
            <h1 className="text-yellow-300">Thsi is AddProduct</h1>
        </>
    );
};

export default AddProduct;