export const metadata = {
    title: 'Profile| Next App',
    description: 'Generated by create next app',
  }
const ProfilePage =()=> {
    return (
        <div>
            <h1>Profile</h1>
        </div>
    );
};

export default ProfilePage;