export const metadata = {
    title: 'Dashboard | Next App',
    description: 'Generated by create next app',
  }
const DashboardPage =()=> {
    return (
        <div>
            <h1 className="text-red-500">Thsi is Dashboard</h1>
        </div>
    );
};

export default DashboardPage;