export const metadata = {
  title: 'Blogs | Next App',
  description: 'Generated by create next app',
}



const SignleBlog = ({ params }) => {
    console.log(params.segments);
    const [year , id] =params.segments || [];
  return (
    <div>SignleBlog {year || new Date().getFullYear() } for {id} </div>
  )
}

export default SignleBlog;